### ISSUE TITLE
Simple but powerful variables usage

### ISSUE THREAD

**Issue by pablodav** [vaidik/ansible-tutorial-by-examples#3]
Hello, 

I'm creating this issue as a first contact with you because I think I want to create somthing similar as what you are creating here. 

So if we agree maybe I can help on extending this tutorial. 

First thing missing on ansible usage for new users is just a real introduction to usage of already existing roles and best practices on howto correctly use variables without modifying roles or playbooks (only variables to fit their needs). 

So is this tutorial with that objetive? help new users to use what already exists and use best practices only for usage? 

I have done a lot of good work in my environment creating a simple but powerfull structure that I'm would like to share. 

In the variables: 
-----------------

original doc: 

http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

Doesn't clarify best option, only gives all options. 

On my examples: https://pablodav.github.io/post/graylog/logstash_input/#preparing-the-variables 

Use the variables in simple structure, avoid the use of complex or too many different places to place the variables. Use these places: 

```
group_vars/groupname/role_vars
host_vars/hostname/role_vars
```
What other useful example could I use with this kind of structure? 

The `ntp_server` example:

In the case we have two different locations, and we have an `ntp_server` on each location, so we want to use different server on each location for our clients. 

So define two new groups for your hosts (you can have multiple groups per host): 

Suppose you have `Inventory/production` var:

```ini
[L01]
serverx

[L02]
servery

```

Then define `ntp_server_var: Address` on each group, where Address changes on each group:

```
group_vars/L01/ntp_vars
group_vars/L02/ntp_vars
```

The role will use correctly the var for each location. 

There are 2 more things that I'm would like to include in other issues and ofcourse I'm will fork and edit the tutorial if we agree with the things that need to be done here. 

How we should instruct in installing roles, example: 
--------------------------------------------------------

https://pablodav.github.io/post/graylog/logstash_input/#requirements-ansible 

And howto use the playbooks structure: 
--------------------------------------------

https://pablodav.github.io/post/graylog/logstash_input/#preparing-the-playbook-to-run-the-roles

I use to have

```
├── roles.ansible_control.yml
├── roles.appserver.yml
├── roles.burp_servers.yml
├── roles.graylog2.yml
├── roles.infra.yml
├── roles.monitoring.yml
├── roles.mysql_servers.yml
├── roles.redmine_servers.yml
├── roles.velneo.yml
├── site_all.yml
```
and site_all.yml has some similar format like:

```yaml
# Databases:

- include: roles.mysql_servers.yml

# Infra apps:

- include: roles.burp_servers.yml

- include: roles.monitoring.yml

- include: roles.infra.yml

# Business apps:

- include: roles.velneo.yml

- include: roles.appserver.yml
```

for example the graylog vars are:

```yaml

- name: Apply logstash for graylog2 servers
  hosts: graylog2_servers
  become: yes

  roles:

    - role: ansible-logstash
      tags:
        - role::logstash
        - graylog2_servers

```

so there is lot of flexibility in this way
I can call site_all and use --tags tagx,y,z
I can call only roles.databases.yml
or roles.databases.yml --tags xx
also use tags that could be inside some specific task (not used normally because the structure is flexible enough as it is)
also you could tags the - include roles.rolex.yml I think, but never needed it so didn't try.
using ansible.cfg you could also change the structure of folders

What do you think?
